# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c835957dbf99d0cc238a708f3a4745480052164388fac469c5de3c33b5a8c4d7dc041ebd4d468e4b3dec55d8f64d6be889978afd205542c9576eaf538c02b7

test:
  secret_key_base: 116a5315daf7a090940514ec878f1c463e369bf08d57539bbebaa6d5907e422fbc34129c062c26ba94932fa5e206ef74ba4827af28e1ca36ed0bbf64842bd428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
